#!/bin/bash 
wget https://pro.fontawesome.com/releases/v5.5.0/css/all.css -P ./css
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-brands-400.eot -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-brands-400.woff2 -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-brands-400.woff -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-brands-400.ttf -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-brands-400.svg -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-light-300.eot -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-light-300.woff2 -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-light-300.woff -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-light-300.ttf -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-light-300.svg -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-regular-400.eot -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-regular-400.woff2 -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-regular-400.woff -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-regular-400.ttf -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-regular-400.svg -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-solid-900.eot -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-solid-900.woff2 -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-solid-900.woff -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-solid-900.ttf -P ./webfonts
wget https://pro.fontawesome.com/releases/v5.5.0/webfonts/fa-solid-900.svg -P ./webfonts